services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - front-back

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@db:3306/$MYSQL_DATABASE
    depends_on:
      db:
        condition: service_healthy
    networks:
      - front-back
      - internals

  db:
    image: mysql:9
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - internals
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 3s
      start_interval: 2s
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8002:8080"
    # environment:
      # - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - front-back
      - internals

networks:
  front-back:
  internals:
