services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - front-back

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - nats
    networks:
      - front-back
      - internals

  db:
    image: mysql:9
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - internals

  nats:
    image: nats:2.11-alpine
    networks:
      - internals


networks:
  front-back:
  internals:
